image: registry.cloud.fits/fits/builder:7-dev-81ee9dfc812aa7f7320ca43f63c6d9d5b5a9be87

stages:
    - build

before_script:
  - mc config host add fits https://blobstore.fi-ts.io $ACCESS_KEY "${SECRET_KEY}"

metal-hammer:
  stage: build
  script:
    - make generate-client
    - docker-make --no-push --Lint
    - mkdir images
    - mv metal-hammer-initrd.img.lz4 images
    - cp cmdline images/metal-hammer-cmdline
    - mc cp --recursive images fits/metal
  only:
    - master
