image: registry.cloud.fits/fits/builder:7-dev-81ee9dfc812aa7f7320ca43f63c6d9d5b5a9be87

stages:
    - build

before_script:
  - mc config host add fits https://blobstore.fi-ts.io $ACCESS_KEY "${SECRET_KEY}"

metal-hammer:
  stage: build
  script:
    - docker-make --no-push --Lint
    - mkdir -p images/metal-hammer
    - md5sum metal-hammer-initrd.img.lz4 > metal-hammer-initrd.img.lz4.md5
    - mv metal-hammer-initrd.img.lz4* images/metal-hammer
    - mc cp --recursive images fits/metal
  only:
    - master
metal-hammer-tag:
  stage: build
  script:
    - docker-make --no-push --Lint
    - mkdir -p images/metal-hammer
    - mv metal-hammer-initrd.img.lz4 metal-hammer-initrd-${CI_COMMIT_TAG}.img.lz4
    - md5sum metal-hammer-initrd-${CI_COMMIT_TAG}.img.lz4 > metal-hammer-initrd.img-${CI_COMMIT_TAG}.lz4.md5
    - mv metal-hammer-initrd-${CI_COMMIT_TAG}.img.lz4* images/metal-hammer
    - mc cp --recursive images fits/metal
  only:
    - tags
