image: registry.cloud.fits/fits/buildtools:1

stages:
  - build

before_script:
  - mc config host add fits https://blobstore.fi-ts.io $ACCESS_KEY "${SECRET_KEY}"
  - docker-make --no-push --Lint
  - mkdir -p images/metal-hammer
after_script:
  - mc cp --recursive images fits/metal

metal-hammer-master:
  stage: build
  script:
    - md5sum metal-hammer-initrd.img.lz4 > metal-hammer-initrd.img.lz4.md5
    - mv metal-hammer-initrd.img.lz4* images/metal-hammer
  only:
    - master

metal-hammer-tag-or-branch:
  stage: build
  script:
    - mv metal-hammer-initrd.img.lz4 metal-hammer-initrd-${CI_COMMIT_REF_NAME}.img.lz4
    - md5sum metal-hammer-initrd-${CI_COMMIT_REF_NAME}.img.lz4 > metal-hammer-initrd.img-${CI_COMMIT_REF_NAME}.lz4.md5
    - mv metal-hammer-initrd-${CI_COMMIT_REF_NAME}.img.lz4* images/metal-hammer
  except:
    - master
