image: registry.cloud.fits/fits/builder:7-dev

stages:
    - build

before_script:
  - mc config host add fits https://blobstore.fi-ts.io $ACCESS_KEY "${SECRET_KEY}"

metal-hammer:
  stage: build
  script:
    - docker-make --no-push
    - mkdir images
    - mv metal-hammer-initrd.img.gz images
    - cp cmdline images/metal-hammer-cmdline
    - mc cp --recursive images fits/metal
  only:
    - master
