image: registry.cloud.fits/fits/builder:7-dev-81ee9dfc812aa7f7320ca43f63c6d9d5b5a9be87

stages:
    - build

# Disabled by leading dot.
.compile:
  stage: build
  script:
    - docker-make -s --exclude-linting-rules rule3
    - linuxkit build pxeboot.yaml
    - mkdir images
    - mv pxeboot-kernel pxeboot-initrd.img pxeboot-cmdline images
    - mc cp --recursive images fits/metal
  only:
    - master

.compile-uroot:
  stage: build
  variables:
    GOPATH: "/go"
  script:
    - mkdir -p ${GOPATH}/pkg ${GOPATH}/bin ${GOPATH}/src/github.com/u-root
    - cd ${GOPATH}/src/github.com/u-root && git clone https://github.com/u-root/u-root && cd u-root && go build -o $GOPATH/bin/u-root
    - cd ${CI_PROJECT_DIR}
    - yum install -y rng-tools e2fsprogs dosfstools gdisk which
    - make
    - mkdir images
    - linuxkit build metal-hammer.yaml && rm metal-hammer-initrd.img
    - make uroot
    - mv metal-hammer-kernel metal-hammer-initrd.img metal-hammer-cmdline images
    - mc cp --recursive images fits/metal
  only:
    - master

compile-uroot-debian:
  image: golang:1.11-stretch
  stage: build
  script:
    - apt update && apt install -y rng-tools e2fsprogs dosfstools gdisk make git curl gcc
    - curl -fsSL https://dl.minio.io/client/mc/release/linux-amd64/mc -o /usr/local/bin/mc
    - chmod +x /usr/local/bin/mc
    - mc config host add fits https://blobstore.fi-ts.io $ACCESS_KEY "${SECRET_KEY}"
    - curl -fsSL https://github.com/linuxkit/linuxkit/releases/download/v0.6/linuxkit-linux-amd64 -o /usr/local/bin/linuxkit
    - chmod +x /usr/local/bin/linuxkit
    - go get github.com/u-root/u-root
    - linuxkit build metal-hammer.yaml && rm metal-hammer-initrd.img
    - make uroot
    - gzip metal-hammer-initrd.img
    - mkdir images
    - mv metal-hammer-kernel metal-hammer-initrd.img.gz metal-hammer-cmdline images
    - mc cp --recursive images fits/metal
  only:
    - master
