image: registry.cloud.fits/fits/builder:7-dev-81ee9dfc812aa7f7320ca43f63c6d9d5b5a9be87

stages:
    - build

before_script:
  - mc config host add fits https://blobstore.fi-ts.io $ACCESS_KEY "${SECRET_KEY}"

compile:
  stage: build
  script:
    - docker-make -s --exclude-linting-rules rule3
    - linuxkit build pxeboot.yaml
    - mkdir images
    - mv pxeboot-kernel pxeboot-initrd.img pxeboot-cmdline images
    - mc cp --recursive images fits/metal
  only:
    - master
